name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint and enforce minimum score
        run: |
          FILES=$(git ls-files '*.py')
          if [ -z "$FILES" ]; then
            echo "No Python files to lint."
            exit 0
          fi

          # Run pylint and capture output
          pylint_output=$(pylint $FILES)
          echo "$pylint_output"

          # Extract score
          score=$(echo "$pylint_output" | grep "Your code has been rated at" | sed -E 's/.* ([0-9]+\.[0-9]+)\/10.*/\1/')

          echo "Pylint score: $score"

          # Fail if score is below 7.0
          score_check=$(echo "$score < 7.0" | bc -l)
          if [ "$score_check" -eq 1 ]; then
            echo "❌ Pylint score is below threshold (70%). Failing the build."
            exit 1
          else
            echo "✅ Pylint score is above threshold (70%)."
          fi
